name: Test

on:
  - push
  - pull_request

jobs:

  test_go:
    name: Run Go tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...

  test_container:
    name: Build a container test image
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Docker
        run: docker build . --file Dockerfile --tag talos-vmtoolsd:test
